pipeline {
    agent any

    environment {
        FIREBASE_TOKEN = credentials('firebase-token')
    }

    stages {
        stage('Build') {
            steps {
                echo 'Installing Firebase Tools...'
                sh 'npm install -g firebase-tools'
            }
        }
        stage('Deploy to Testing') {
            steps {
                echo 'Deploying to Testing Environment...'
                sh 'firebase deploy --only hosting --project testing --token $FIREBASE_TOKEN'
            }
        }
        stage('Deploy to Staging') {
            steps {
                echo 'Deploying to Staging Environment...'
                sh 'firebase deploy --only hosting --project staging --token $FIREBASE_TOKEN'
            }
        }
        stage('Deploy to Production') {
            steps {
                echo 'Deploying to Production Environment...'
                sh 'firebase deploy --only hosting --project production --token $FIREBASE_TOKEN'
            }
        }
    }
}